### ISSUE TITLE
Fix Web Explorer meta description UOS to U°OS

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/uos#17]
## Current Behavior
It's a minor fix to keep this consistent across all docs/media. UOS is the token ticker, U°OS is the framework/blockchain name.

## Environment
Client independent

## Steps to reproduce
1. View meta for explorer.uos.network (I noticed this when sending the link in Telegram that fetches title)

2. See:

```
<meta name="description" content="UOS Tracker, Real time viewer for UOS Blockchain">
```

and

```
<title>UOS Tracker | Real time viewer for UOS Blockchain</title>
```

## Expected behavior
Please change to:

```
<meta name="description" content="U°OS Tracker | Real time viewer for U°OS Blockchain">
```

and

```
<title>U°OS Tracker | Real time viewer for U°OS Blockchain</title>
```

Also check this, not sure if needs to be changed or kept as is:
```
<meta name="author" content="Cesar Rodriguez">
```

**Comment by coodi** [comment]
changes are made
